# Why is Numpy faster than Lists?

* ## Becasuse Numpy require less storage space, it is faster to read less bytes in memory as oppossed in list
* ## Numpy uses Contigous Memory
    * SIMD Vector Processing (Single Instrucions Multiple Data)
    * Effective Cache Utilization
* In List we can do insertion, deletion, apending, concatenation, etc. In numpy we can do all that plus lot more...

### Applications of Numpy
* Mathematics (MATLAB Replacement)
* Plotting (Matplotlib)
* Backend (Pandas, Connect 4, Digital Photography)
* Machine Learning


In [1]:
import numpy as np

## The Basics

In [3]:
# initialising an array
a = np.array([1,2,3,4,6])
a

array([1, 2, 3, 4, 6])

In [5]:
b = np.array([[45,66,8],[98,34,77]])
b

array([[45, 66,  8],
       [98, 34, 77]])

In [6]:
# Get the dimensions of the arrays

In [7]:
a.ndim

1

In [8]:
# Get the shape
a.shape

(5,)

In [9]:
b.shape

(2, 3)

In [10]:
# checking the memory...
a.dtype

dtype('int32')

In [11]:
# Get the size
a.itemsize

4

In [13]:
# Get the total size...
a.nbytes

20

## Accessing/Changing Specific Elements, rows, columns, etc...

In [14]:
a = np.array([[2,343,6,77,44,66,77],[77,88,44,3,66,88,55]])
a

array([[  2, 343,   6,  77,  44,  66,  77],
       [ 77,  88,  44,   3,  66,  88,  55]])

In [15]:
a.shape

(2, 7)

In [16]:
# [r,c]
a[1,6]

55

In [17]:
# using negative index
a[-2,-7] # printing the first elem, in the first row

2

In [19]:
# getting a specific row..
a[0,:]

array([  2, 343,   6,  77,  44,  66,  77])

In [20]:
# Getting a specific column...
a[:,3]

array([77,  3])

In [24]:
# [row,start_index:end_index:stepsize]
a[0,1:6:2] # start_index is included but end_index is excluded..

array([343,  77,  66])

In [26]:
# printing backward...
a[0,6:1:-2]

array([77, 44,  6])

In [27]:
# Replacing Numbers in arrays
a[:,2] = 4
a

array([[  2, 343,   4,  77,  44,  66,  77],
       [ 77,  88,   4,   3,  66,  88,  55]])

In [28]:
a[:,3] = [1,3]

In [29]:
a

array([[  2, 343,   4,   1,  44,  66,  77],
       [ 77,  88,   4,   3,  66,  88,  55]])

In [41]:
d3 = np.array([[[3,22,55,33],[88,45,64,34]],[[23,76,-97,90],[90,908,23,55]],[[3,22,55,33],[88,45,64,34]]])

In [42]:
d3

array([[[  3,  22,  55,  33],
        [ 88,  45,  64,  34]],

       [[ 23,  76, -97,  90],
        [ 90, 908,  23,  55]],

       [[  3,  22,  55,  33],
        [ 88,  45,  64,  34]]])

In [44]:
d3.shape

(3, 2, 4)

In [45]:
a = np.array([[34,66,33],[98,22,55],[990,3,4],[3,7,3]])
a
a.shape

(4, 3)

In [47]:
# indexing on advanced dimensional arrays...
d3[:,1,:]

array([[ 88,  45,  64,  34],
       [ 90, 908,  23,  55],
       [ 88,  45,  64,  34]])

In [48]:
d3[2,:,2]

array([55, 64])

## initialising different types of arrays


In [52]:
# all 0s matrix
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [54]:
# All 1s is matrix..
np.ones((4,2,3),dtype='int32')

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [56]:
# creating any other number...
np.full((2,3),99,dtype='float32')

array([[99., 99., 99.],
       [99., 99., 99.]], dtype=float32)

In [57]:
# Any Other number (full -like)
np.full(a.shape,5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

## random number arrays


In [61]:
np.random.rand(4,2)

array([[0.19629277, 0.0390647 ],
       [0.65819068, 0.99071223],
       [0.07702495, 0.8080819 ],
       [0.45074249, 0.83894848]])

In [63]:
np.random.rand(4,2,4) # numbers are between 0 and 1

array([[[0.73657488, 0.84917297, 0.06588628, 0.05439141],
        [0.1366021 , 0.4153541 , 0.05336168, 0.5676535 ]],

       [[0.27709707, 0.22949194, 0.65775094, 0.16016341],
        [0.53363631, 0.5739424 , 0.25155375, 0.14217048]],

       [[0.25303061, 0.45990607, 0.85250986, 0.03801354],
        [0.38322766, 0.55829471, 0.81244161, 0.95599302]],

       [[0.61400648, 0.51984775, 0.31202281, 0.49414692],
        [0.08715181, 0.3362958 , 0.92996262, 0.20590963]]])

In [68]:
a

array([[ 34,  66,  33],
       [ 98,  22,  55],
       [990,   3,   4],
       [  3,   7,   3]])

In [69]:
# Random sample
np.random.random_sample(a.shape)

array([[0.28783868, 0.70706075, 0.71159306],
       [0.66169897, 0.65413184, 0.5820845 ],
       [0.77565919, 0.84810824, 0.33033639],
       [0.63587001, 0.1746785 , 0.07335147]])

In [70]:
np.random.rand(4,2)

array([[0.15263965, 0.83914276],
       [0.09179422, 0.62080933],
       [0.9812026 , 0.01904961],
       [0.18666009, 0.72169664]])

In [72]:
# random integer values..
np.random.randint(7,size=(3,3))

array([[2, 5, 2],
       [5, 4, 3],
       [0, 6, 0]])

In [73]:
np.random.randint(3,8,size=(3,4,3))

array([[[4, 5, 3],
        [7, 5, 4],
        [7, 4, 3],
        [5, 7, 6]],

       [[7, 5, 6],
        [5, 7, 4],
        [4, 7, 6],
        [5, 4, 3]],

       [[5, 4, 7],
        [7, 4, 4],
        [4, 6, 3],
        [3, 5, 3]]])

In [75]:
# identity matrix -> All diagonal values are ones...
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Converting a dimension in numpy

In [79]:
# 2d
arr = np.array([[1,3,4]])
r1 = np.repeat(arr,3,axis=0)
r1

array([[1, 3, 4],
       [1, 3, 4],
       [1, 3, 4]])

In [80]:
# 3 d by repeating an array
arr = np.array([[[1,3,4]]])
r1 = np.repeat(arr,3,axis=0)
r1

array([[[1, 3, 4]],

       [[1, 3, 4]],

       [[1, 3, 4]]])

In [81]:
r1.shape

(3, 1, 3)

In [89]:
pic = np.ones(shape=(5,5))

In [90]:
pic

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [91]:
pic[1:4,1:4] = 0
pic

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [92]:
pic[2,2] = 9
pic

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [94]:
# a more intuitive way
output = np.ones((5,5))
z = np.zeros((3,3))
z[1,1] = 9
output[1:-1,1:-1] = z
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [95]:
# copying files in python...
a = np.array([1,2,3])
b = a
b[0] = 100 # this one is deep copy... uses pointer-like-copying
print(a)

[100   2   3]


In [96]:
a = np.array([2,3,4,5])
b = a.copy()
b[0] = 100
print(b)
print(a) # now copying from a does not change a...

[100   3   4   5]
[2 3 4 5]


## Mathematics in Numpy

In [97]:
a =np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [98]:
a + 2

array([3, 4, 5, 6])

In [99]:
a += 2
a

array([3, 4, 5, 6])

In [100]:
a+= 2

In [101]:
a

array([5, 6, 7, 8])

In [102]:
a/2

array([2.5, 3. , 3.5, 4. ])

In [103]:
a*2

array([10, 12, 14, 16])

In [104]:
b = np.array([1,0,1,3])
b

array([1, 0, 1, 3])

In [105]:
b + 1

array([2, 1, 2, 4])

In [106]:
b+a

array([ 6,  6,  8, 11])

In [107]:
a

array([5, 6, 7, 8])

In [108]:
b

array([1, 0, 1, 3])

In [109]:
a += b
a

array([ 6,  6,  8, 11])

In [110]:
b = np.array([2,3,2,3,3])
b

array([2, 3, 2, 3, 3])

In [112]:
a

array([ 6,  6,  8, 11])

In [114]:
a ** 2 # raising the array to power 2

array([ 36,  36,  64, 121])

In [116]:
# Taking the sin of a
np.sin(a) # returns the sin of all the values in the array

array([-0.2794155 , -0.2794155 ,  0.98935825, -0.99999021])

In [117]:
np.cos(a)

array([ 0.96017029,  0.96017029, -0.14550003,  0.0044257 ])

In [119]:
np.__version__ # checking the version of numpy


'1.23.5'

## Linear Algebra with Numpy

In [121]:
a = np.full((2,3),1)

In [122]:
a

array([[1, 1, 1],
       [1, 1, 1]])

In [123]:
b= np.full((3,2),2)
b

array([[2, 2],
       [2, 2],
       [2, 2]])

#### In linear Algebra the rows of the first  matrix must be equal to the columns of the second one...

In [126]:
b = np.full((3,2),2)
print(a)

[[1 1 1]
 [1 1 1]]


In [128]:
#a*b # cannot work this way for direct mult
np.matmul(a,b)

array([[6, 6],
       [6, 6]])

In [133]:
# Find the determinant...
c = np.identity(4)
print(c)
np.linalg.det(c)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


1.0

`https://docs.scipy.org/doc/numpy/reference/routines.linalg.html

### Statitics with Numpy

In [134]:
stats = np.array([[2,44,66,44],[88,99,3,55]])
stats


array([[ 2, 44, 66, 44],
       [88, 99,  3, 55]])

In [137]:
np.min(stats)

2

In [138]:
np.max(stats,axis=0) # 0 for column and 1 for row

array([88, 99, 66, 55])

In [139]:
np.sum(stats)

401

In [141]:
np.sum(stats,axis=0) # sum all columns

array([ 90, 143,  69,  99])

In [142]:
np.sum(stats, axis=1) # sum all rows.. 

array([156, 245])

## Reorganizing Arrays

In [1]:

before = np.array([[1,4,33,55],[99,8,4,3]])
before

<IPython.core.display.Javascript object>

array([[ 1,  4, 33, 55],
       [99,  8,  4,  3]])

In [2]:
after = before.reshape(8,1)

In [3]:
after

array([[ 1],
       [ 4],
       [33],
       [55],
       [99],
       [ 8],
       [ 4],
       [ 3]])

In [4]:
before.reshape(4,2)

array([[ 1,  4],
       [33, 55],
       [99,  8],
       [ 4,  3]])

### Stacking


In [7]:
# vertical stacking
v1 = np.array([2,44,55,3])
v2 = np.array([9,23,55,89])
np.vstack([v1,v2,v1,v2])

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

array([[ 2, 44, 55,  3],
       [ 9, 23, 55, 89],
       [ 2, 44, 55,  3],
       [ 9, 23, 55, 89]])

In [8]:
np.vstack(np.array([v2,v1,v1]))

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

array([[ 9, 23, 55, 89],
       [ 2, 44, 55,  3],
       [ 2, 44, 55,  3]])

In [9]:
# Horizontal Stacking...
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [10]:
np.hstack([h1,h2])

<IPython.core.display.Javascript object>

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## Other Operations...

In [12]:
# Loading data from text file using Numpy ...excluding pandas
file_data = np.genfromtxt('data.txt',delimiter=',')
file_data = file_data.astype('int32')
file_data

<IPython.core.display.Javascript object>

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

## Boolean Masking & Advaced Masking

In [13]:
file_data[file_data > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [16]:
# indexing with a list in Numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a

<IPython.core.display.Javascript object>

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
a[[1,2,8]]

array([2, 3, 9])

In [18]:
np.any(file_data > 50, axis = 0) # columns

<IPython.core.display.Javascript object>

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [19]:
np.all(file_data > 50, axis = 0) # returns instance where all columns values are greter than 50

<IPython.core.display.Javascript object>

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [20]:
np.all(file_data > 50, axis = 1) # returns instance where all rows values are greter than 50

<IPython.core.display.Javascript object>

array([False, False, False])

In [30]:
# checking for multiple conditions...
(~((file_data > 50) & (file_data < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [ ]:
a[[0,4,5],3:]